kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: oven/bun:latest
    commands:
      - cd frontend
      - bun --bun install

  - name: build
    image: oven/bun:latest
    commands:
      - cd frontend
      - bun --bun vite build

  - name: deploy
    image: drillster/drone-rsync
    settings:
      hosts: [ "192.168.255.209" ]
      port: 22
      user: drone
      key:
        from_secret: ssh_key
      recursive: true
      delete: true
      source: ./frontend/dist/*
      target: ~/
