kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: oven/bun:latest
    commands:
      - cd frontend
      - bun --bun install

  - name: build
    image: oven/bun:latest
    commands:
      - cd frontend
      - bun --bun vite build
